server:
  port: 8006
spring:
  application:
    name: cloudconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brijesh-2203/config-server
          clone-on-start: true