server:
  port: 8002
spring:
  application:
    name: addressService
  cloud:
     config:
        enabled: true
        uri: http://localhost:8006   
eureka:
  instance:
    hostname: localhost
   
 