server:
  port: 8004


spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/userServiceFallBack
        - id: addressService
          uri: lb://addressService
          predicates:
            - Path=/address/**
          filters:
            - name: CircuitBreaker
              args:
                name: addressService
                fallbackUri: forward:/addressServiceFallBack

hystrix:
  command:
    fallbackCmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream